### ISSUE TITLE
[CS:GO] Download issue

### ISSUE THREAD

**Issue by EE171799845** [srpg/Zombie#1]
I don't know if it's my problem or the plug-in problem

![image](https://user-images.githubusercontent.com/101020251/156937041-2f974a53-7d22-410c-a190-ec60cb1d552a.png)

**Comment by srpg** [comment]
I think i know the problem. It seems i accidently have added bz2 format the materials files, which is used at fastdl, but without fastdl bz2 format is invalid for be able download via server

**Comment by srpg** [comment]
Try newest version i just made a [commit](https://github.com/srpg/Zombie/commit/225bbd3d5ae1ebbdd31e91538b924f77fd312c05) that fixes the download files

**Comment by EE171799845** [comment]
It's really great. Thank you very much. I'll try again☺

srpg ***@***.***> 于2022年3月7日周一 03:26写道：

**Comment by EE171799845** [comment]
It seems that the web page 404 is, but it doesn't matter. I will continue
to wait. Thank you very much

伊诚惠 ***@***.***> 于2022年3月7日周一 03:46写道：

**Comment by srpg** [comment]
You can download the new version from the code button
